### ISSUE TITLE
Can be spoofed

### ISSUE THREAD

**Issue by fisakhan** [habom2310/Heart-rate-measurement-using-camera#12]
Thanks for sharing a great piece of work. However, it shows heart rate for a paper printed face. Principally, it shouldn't show show heart rate for a paper. How can we handle this situation in the code?

**Comment by habom2310** [comment]
Thank you for your suggesstion. I think that it will need something like face liveness detection to prevent situations like this. But, in the scope of this project, I will only deal with measuring heart rate so you can search other github projects such as I found [here](https://github.com/ee09115/spoofing_detection) for more information.
