### ISSUE TITLE
How do I get the forehead area into a rectangle instead of cheeks

### ISSUE THREAD

**Issue by canibal1** [habom2310/Heart-rate-measurement-using-camera#17]
**### How do I get the forehead area into a rectangle instead of cheeks? Or both of same time**

**Comment by habom2310** [comment]
The rectangle or Region of Interest (ROI) is extracted using the 68 landmarks. For example, the left cheek is defined as a rectangle having top left corner: (x30,y5), bottom right conner (x49,y34). 

![image](https://user-images.githubusercontent.com/31272516/84565428-7c52c200-adac-11ea-9f6b-644e4ebd3363.png)

The forehead does not fall within the bound of the landmarks, so I recommend to get top left corner (x21, y21 + 100), bottom right corner (x24, y24).

**Comment by canibal1** [comment]
Thank you sir :)
