### ISSUE TITLE
Data preprocessing choices

### ISSUE THREAD

**Issue by PartyTrix** [habom2310/Heart-rate-measurement-using-camera#2]
Hi, 

Thank you very much for the excellent implementation! 
I had a question regarding the pre-processing of the signal. You detrend and normalize the signal before you apply the butterworth filter. As I am no expert, I was wondering if this is done for the visualization only - or that it is a good practice to normalize & detrend before applying the butterworth filter.
(For my application, I'm not interested in the fft frequencies - but I want to later extract the HRV from the remote PPG signal - thus the main objective is to get a reasonably clean signal. Also I use the POS-rPPG implementation as described by Wang, W., den Brinker, A. C., Stuijk, S., & de Haan, G. (2017). Algorithmic principles of remote-PPG.).

Thanks,
R

**Comment by habom2310** [comment]
Hi,

After detrending and normalization, the signal is quite like HR signal and with fft, I can extract the HR. Here, the butterworth filter is used for visualization only, indeed it just does an ifft to get the signal after filtered for display. But if you don't use fft, I recommend to filter before doing next processing steps, it will help you to get cleaner HR signal.

**Comment by PartyTrix** [comment]
Thank you for your response.
Now that I think of it, it just makes sense to clean the signal around the expected heartrate - even for use in some machinelearning application after. 
Thanks for sharing your work!
