### ISSUE TITLE
new_update , test signal processing & fa.align

### ISSUE THREAD

**Issue by aminrezaei-img** [habom2310/Heart-rate-measurement-using-camera#26]
Hi, I tried to run the updated code but for some unknown reason it crashes, apparently, it is not reading frame or face data! 

any suggestions?

Files\Heart-rate-measurement-using-camera-master\Heart-rate-measurement-using-camera-master\new_update\face_utilities.py", line 114, in face_alignment
    M = cv2.getRotationMatrix2D(eyesCenter, angle, scale)
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type
[ WARN:1@3.529] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

I also had some issues with face alignment 
face_frame = self.fa.align(frame,gray,rects[0]) # align face
as it prevents the actual code from running so had to comment on it and then it worked. but I was wondering does muting it affect the results?

**Comment by vaibhavtasgaonkar** [comment]
I was facing the same error and later on solved the error. You can solve the problem by using int i.e integer for x and y coordinates in the circle function.  For this, you have to edit file which comes pre-installed with python. To find this file just use the traceback given by pyton. 
![image](https://user-images.githubusercontent.com/69762836/161302842-d38d86b3-5fb1-4e63-86b3-d034d140d691.png)

**Comment by habom2310** [comment]
fixed with the new update
