### ISSUE TITLE
Library installation issue

### ISSUE THREAD

**Issue by vincentronca** [habom2310/Heart-rate-measurement-using-camera#4]
Hi, 

I'm facing with some issues installing the requested libraries. I can't install dlib, opencv. Which kind of OS are you using? And which python version?
Is it possible to provide some link to download the good library version?

Thank you very much, your work seems very promising.
Vincenzo

**Comment by habom2310** [comment]
I'm using window 10 with python 3.5. 
For dlib, I recommend to use the wheel file, you can download it from here https://pypi.org/project/dlib/18.17.100/#files
For opencv, you can install it by `pip install opencv-python`

**Comment by vincentronca** [comment]
Hi, thank you very much. I Installed all the libraries except PyQt4. I tried even to look for the wheel file but it seems that it's only available for Python 3.4.
Do you have any suggestion?

**Comment by habom2310** [comment]
try this out: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4

**Comment by vincentronca** [comment]
thank you very much. The tool is working very well. In this regard, I would like to ask you more detailed instructions about how to get the log containing the HR data recorded during the session. Thanks again!

**Comment by habom2310** [comment]
You can use new update in https://github.com/habom2310/Heart-rate-measurement-using-camera/tree/master/new_update. You can get HR log of a video.
